version: "3.8"

services:

  backend:
    build: ./backend
    container_name: nuel_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/nuelbank
    depends_on:
      - mongo
    networks:
      - nuel_network

  mongo:
    image: mongo:6.0
    container_name: nuel_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - nuel_network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: nuel_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    networks:
      - nuel_network

volumes:
  mongo_data:

networks:
  nuel_network:
    driver: bridge
